const icons = {
  figma: <>icon</>,
  git: <>icon</>,
  file: <>icon</>,
  download: <>icon</>,
  gitHub: <>github</>,
  code: <>icon</>,
  clap: <>icon</>,
  externalLink: <>icon</>,
  api: <>icon</>,
  node: <>icon</>,
  npm: <>icon</>,
  react: <>icon</>,
  sass: <>icon</>,
  css: <>icon</>,
  linkedIn: <>icon</>,
  cypress: <>icon</>,
  express: <>icon</>,
  graphql: <>icon</>,
  hasura: <>icon</>,
  html: <>icon</>,
  es6: <>icon</>,
  javascript: <>icon</>,
  jest: <>icon</>,
  nextjs: <>icon</>,
  redux: <>icon</>,
  typescript: <>icon</>,
  async: <>icon</>,
  xd: <>icon</>,
  photoshop: <>icon</>,
  illustrator: <>icon</>,
  socketio: <>icon</>,
  menu: <>icon</>,
  close: <>icon</>,
  commit: <>icon</>,
  views: <>icon</>,
  thumbsUp: <>icon</>,
  arrowDown: <>icon</>,
  arrowRight: <>icon</>,
  arrowRightNarrow: <>icon</>,
  email: <>icon</>,
} as const;

// const icons = {
//   figma: <FaFigma />,
//   git: <FaGitAlt />,
//   file: <CgFileDocument />,
//   download: <CgSoftwareDownload />,
//   gitHub: <FiGithub />,
//   code: <HiOutlineCode />,
//   clap: <Clap />,
//   externalLink: <FiExternalLink />,
//   api: <VscJson />,
//   node: <FaNodeJs />,
//   npm: <FaNpm />,
//   react: <FaReact />,
//   sass: <FaSass />,
//   css: <SiCss3 />,
//   linkedIn: <FaLinkedinIn />,
//   cypress: <SiCypress />,
//   express: <SiExpress />,
//   graphql: <SiGraphql />,
//   hasura: <SiHasura />,
//   html: <SiHtml5 />,
//   es6: <SiJavascript />,
//   javascript: <SiJavascript />,
//   jest: <SiJest />,
//   nextjs: <SiNextdotjs />,
//   redux: <SiRedux />,
//   typescript: <SiTypescript />,
//   async: <TiArrowSync />,
//   xd: <AdobeXd />,
//   photoshop: <AdobePhotoshop />,
//   illustrator: <AdobeIllustrator />,
//   socketio: <SiSocketdotio />,
//   menu: <RiMenu3Line />,
//   close: <RiCloseLine />,
//   commit: <FiGitCommit />,
//   views: <MdOutlineRemoveRedEye />,
//   thumbsUp: <FiThumbsUp />,
//   arrowDown: <FiArrowDown />,
//   arrowRight: <MdOutlineArrowRightAlt />,
//   arrowRightNarrow: <HiOutlineArrowNarrowRight />,
//   email: <MdOutlineMarkEmailRead />,
// } as const;

export default icons;
