const icons = {
  figma: <></>,
  git: <></>,
  file: <></>,
  download: <></>,
  gitHub: <></>,
  code: <></>,
  clap: <></>,
  externalLink: <></>,
  api: <></>,
  node: <></>,
  npm: <></>,
  react: <></>,
  sass: <></>,
  css: <></>,
  linkedIn: <></>,
  cypress: <></>,
  express: <></>,
  graphql: <></>,
  hasura: <></>,
  html: <></>,
  es6: <></>,
  javascript: <></>,
  jest: <></>,
  nextjs: <></>,
  redux: <></>,
  typescript: <></>,
  async: <></>,
  xd: <></>,
  photoshop: <></>,
  illustrator: <></>,
  socketio: <></>,
  menu: <></>,
  close: <></>,
  commit: <></>,
  views: <></>,
  thumbsUp: <></>,
  arrowDown: <></>,
  arrowRight: <></>,
  arrowRightNarrow: <></>,
  email: <></>,
} as const;

// const icons = {
//   figma: <FaFigma />,
//   git: <FaGitAlt />,
//   file: <CgFileDocument />,
//   download: <CgSoftwareDownload />,
//   gitHub: <FiGithub />,
//   code: <HiOutlineCode />,
//   clap: <Clap />,
//   externalLink: <FiExternalLink />,
//   api: <VscJson />,
//   node: <FaNodeJs />,
//   npm: <FaNpm />,
//   react: <FaReact />,
//   sass: <FaSass />,
//   css: <SiCss3 />,
//   linkedIn: <FaLinkedinIn />,
//   cypress: <SiCypress />,
//   express: <SiExpress />,
//   graphql: <SiGraphql />,
//   hasura: <SiHasura />,
//   html: <SiHtml5 />,
//   es6: <SiJavascript />,
//   javascript: <SiJavascript />,
//   jest: <SiJest />,
//   nextjs: <SiNextdotjs />,
//   redux: <SiRedux />,
//   typescript: <SiTypescript />,
//   async: <TiArrowSync />,
//   xd: <AdobeXd />,
//   photoshop: <AdobePhotoshop />,
//   illustrator: <AdobeIllustrator />,
//   socketio: <SiSocketdotio />,
//   menu: <RiMenu3Line />,
//   close: <RiCloseLine />,
//   commit: <FiGitCommit />,
//   views: <MdOutlineRemoveRedEye />,
//   thumbsUp: <FiThumbsUp />,
//   arrowDown: <FiArrowDown />,
//   arrowRight: <MdOutlineArrowRightAlt />,
//   arrowRightNarrow: <HiOutlineArrowNarrowRight />,
//   email: <MdOutlineMarkEmailRead />,
// } as const;

export default icons;
